sudo: false

language: go

go:
  - "1.13"

install: true
script:
  - echo "baetyl-remote build begin"
  - env GO111MODULE=on make
  - echo "baetyl-remote build end"
  - echo "baetyl uint test begin"
  - env GO111MODULE=on make test GOTESTFLAG=--race
  - echo "baetyl unit test end"
