sudo: false

language: go

go:
  - "1.18"

install: true
script:
  - echo "baetyl-remote build begin"
  - env GO111MODULE=on GOPROXY=https://goproxy.io make
  - echo "baetyl-remote build end"
  - echo "baetyl uint test begin"
  - env GO111MODULE=on GOPROXY=https://goproxy.io make test GOTESTFLAG=--race
  - echo "baetyl unit test end"
